import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const events = [
  // Day 1 Events - 16 total
  {
    eventId: 'd1-registration',
    title: 'Registration & Welcome',
    description: 'Check-in and receive your welcome kit',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T09:00:00'),
    endTime: new Date('2026-02-02T09:30:00'),
    venue: 'Main Entrance',
    status: 'upcoming',
  },
  {
    eventId: 'd1-inaugural',
    title: 'Inaugural Ceremony',
    description: 'Official opening of E-Summit 2026',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T09:30:00'),
    endTime: new Date('2026-02-02T10:30:00'),
    venue: 'Main Auditorium',
    status: 'upcoming',
    speakerName: 'Chief Guest',
  },
  {
    eventId: 'd1-ten-minute-million',
    title: 'The Ten Minute Million',
    description: 'Pitch to VCs for seed funding opportunities. TRL 4+ startups present 10-minute pitches followed by Q&A.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T13:00:00'),
    venue: 'SH-4',
    eligibility: 'TRL 4+ startups',
    prerequisites: 'Pitch deck required (PDF, max 15 slides)',
    status: 'upcoming',
    speakerName: '5 Venture Capitalists',
  },
  {
    eventId: 'd1-angel-roundtable',
    title: 'Angel Investors Roundtable',
    description: 'Present early-stage startup to angel investors for pre-seed funding. 15-minute presentation + Q&A with MVP demonstration.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T14:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: '530, 531',
    eligibility: 'Early stage startups with MVP',
    status: 'upcoming',
    speakerName: '5 Angel Investors',
  },
  {
    eventId: 'd1-pitch-arena',
    title: 'Pitch Arena - Idea to Reality',
    description: 'Early-stage idea pitching platform for first-time founders. 5-minute pitch format, open to idea stage startups.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T13:00:00'),
    venue: 'SH-3, 532, 533, 504',
    eligibility: 'Early stage startups, first-time founders welcome',
    status: 'upcoming',
    speakerName: '3 Industry Mentors',
  },
  {
    eventId: 'd1-incubator-summit',
    title: 'Incubator Summit',
    description: 'Pitch to top incubation centers from Mumbai and Pune for incubation support, mentorship slots, and acceleration guidance.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Multipurpose Hall 1st floor',
    eligibility: 'Early stage startups',
    status: 'upcoming',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd1-ai-buildathon-start',
    title: 'AI Build-A-Thon (Day 1)',
    description: 'Build innovative AI-powered solutions to real-world problems (Continues to Day 2)',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: '216, 217',
    eligibility: 'All pass holders',
    prerequisites: 'Laptop with development environment',
    prizeAmount: 150000,
    status: 'upcoming',
    speakerName: 'Tech Mentors',
  },
  {
    eventId: 'd1-ipl-auction',
    title: 'IPL Auction',
    description: 'Simulate IPL auction mechanics with team building and strategic bidding',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: '505, 506',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd1-biz-arena',
    title: 'Biz Arena Startup League',
    description: 'Team-based business simulation competition with real-world startup challenges',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 520 & 521',
    eligibility: 'All pass holders',
    prizeAmount: 100000,
    status: 'upcoming',
    speakerName: 'Business Mentors',
  },
  {
    eventId: 'd1-startup-youth-conclave',
    title: 'Startup Youth Conclave',
    description: 'Networking session with E-Cell representatives from 40+ colleges across India',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T13:00:00'),
    venue: 'SH-1',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'E-Cell Representatives',
  },
  {
    eventId: 'd1-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop',
    description: 'Hands-on workshop teaching design thinking methodology for problem-solving and innovation',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 522 & 523',
    eligibility: 'Silicon & Quantum Pass holders',
    prerequisites: 'Notepad recommended',
    status: 'upcoming',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd1-finance-marketing',
    title: 'Finance & Marketing Workshop',
    description: 'Master financial planning and marketing strategies for startups',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 524 & 525',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd1-data-analytics',
    title: 'Data Analytics & BDM Workshop',
    description: 'Learn data-driven decision making and business development strategies',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 526 & 527',
    eligibility: 'Silicon & Quantum Pass holders',
    prerequisites: 'Basic Excel knowledge',
    status: 'upcoming',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd1-startup-expo',
    title: 'Startup Expo (Day 1)',
    description: 'Explore booths from innovative startups and connect with founders',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T09:30:00'),
    endTime: new Date('2026-02-02T16:30:00'),
    venue: 'Lobby Area',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-internship-fair',
    title: 'Internship & Job Fair (Day 1)',
    description: 'Meet startups and companies offering internship and job opportunities',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Convocation Hall',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-networking-arena',
    title: 'Networking Arena (Lunch)',
    description: 'Open networking session during lunch - connect with entrepreneurs and investors',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T13:00:00'),
    endTime: new Date('2026-02-02T14:00:00'),
    venue: 'Multipurpose Hall 2nd Floor & Architecture Ground Floor',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-panel-discussion',
    title: 'Panel Discussion & Valedictory',
    description: 'Expert panel discussing trends and future of entrepreneurship, followed by Day 1 closing',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T14:00:00'),
    endTime: new Date('2026-02-02T16:00:00'),
    venue: 'Auditorium',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Industry Leaders',
  },
  
  // Day 2 Events - 15 total
  {
    eventId: 'd2-registration',
    title: 'Day 2 Registration',
    description: 'Check-in for Day 2 events',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T09:00:00'),
    endTime: new Date('2026-02-03T09:30:00'),
    venue: 'Main Entrance',
    status: 'upcoming',
  },
  {
    eventId: 'd2-ten-minute-million',
    title: 'The Ten Minute Million (Day 2)',
    description: 'Day 2 continuation - TRL 4+ startups pitch to VCs for seed funding',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T13:00:00'),
    venue: 'SH-4',
    eligibility: 'TRL 4+ startups',
    prerequisites: 'Pitch deck required (PDF, max 15 slides)',
    status: 'upcoming',
    speakerName: '5 Venture Capitalists',
  },
  {
    eventId: 'd2-angel-roundtable',
    title: 'Angel Investors Roundtable (Day 2)',
    description: 'Day 2 continuation - Angel investor meetings for early-stage startups',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T14:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: '530, 531',
    eligibility: 'Early stage startups with MVP',
    status: 'upcoming',
    speakerName: '5 Angel Investors',
  },
  {
    eventId: 'd2-incubator-summit',
    title: 'Incubator Summit (Day 2)',
    description: 'Day 2 continuation - Pitch to incubation centers for support and mentorship',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Multipurpose Hall 1st floor',
    eligibility: 'Early stage startups',
    status: 'upcoming',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd2-ai-buildathon-final',
    title: 'AI Build-A-Thon (Day 2 Finals)',
    description: 'Final day of hackathon - build completion and judging',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: '216, 217',
    eligibility: 'All pass holders (participants only)',
    prizeAmount: 150000,
    status: 'upcoming',
    speakerName: 'Tech Judges',
  },
  {
    eventId: 'd2-ipl-auction',
    title: 'IPL Auction (Day 2)',
    description: 'Day 2 continuation - IPL auction simulation with final rounds',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: '505, 506',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd2-biz-arena',
    title: 'Biz Arena Startup League (Day 2)',
    description: 'Day 2 continuation - Final rounds of business simulation competition',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 520 & 521',
    eligibility: 'All pass holders',
    prizeAmount: 100000,
    status: 'upcoming',
    speakerName: 'Business Mentors',
  },
  {
    eventId: 'd2-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop (Day 2)',
    description: 'Day 2 continuation - Advanced design thinking sessions',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 522 & 523',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd2-finance-marketing',
    title: 'Finance & Marketing Workshop (Day 2)',
    description: 'Day 2 continuation - Advanced finance and marketing strategies',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 524 & 525',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd2-data-analytics',
    title: 'Data Analytics & BDM Workshop (Day 2)',
    description: 'Day 2 continuation - Advanced data analytics and business development',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 526 & 527',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd2-startup-expo',
    title: 'Startup Expo (Day 2)',
    description: 'Continue exploring innovative startups and their products',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T09:30:00'),
    endTime: new Date('2026-02-03T16:30:00'),
    venue: 'Lobby Area',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd2-internship-fair',
    title: 'Internship & Job Fair (Day 2)',
    description: 'Day 2 continuation - More opportunities from startups and companies',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Convocation Hall',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd2-networking-arena',
    title: 'Networking Arena (Lunch)',
    description: 'Final networking opportunity during lunch with entrepreneurs and investors',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T13:00:00'),
    endTime: new Date('2026-02-03T14:00:00'),
    venue: 'Multipurpose Hall 2nd Floor & Architecture Ground Floor',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd2-closing',
    title: 'Closing Ceremony & Prize Distribution',
    description: 'Award ceremony, winner announcements, and closing remarks for E-Summit 2026',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T17:00:00'),
    endTime: new Date('2026-02-03T18:30:00'),
    venue: 'Auditorium',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Organizing Committee',
  },
];

async function seedEvents() {
  console.log('🌱 Starting event seeding...\n');

  try {
    // First, clear existing events
    console.log('🗑️  Clearing existing events...');
    await prisma.event.deleteMany({});
    console.log('✅ Existing events cleared\n');

    // Insert events
    console.log('📝 Creating events...\n');
    let successCount = 0;
    let errorCount = 0;

    for (const event of events) {
      try {
        await prisma.event.create({
          data: event,
        });
        console.log(`✅ Created: ${event.title} (${event.eventId})`);
        successCount++;
      } catch (error) {
        console.error(`❌ Failed to create ${event.eventId}:`, error);
        errorCount++;
      }
    }

    console.log('\n📊 Seeding Summary:');
    console.log(`✅ Successfully created: ${successCount} events`);
    console.log(`❌ Failed: ${errorCount} events`);
    console.log(`📈 Total: ${events.length} events`);

  } catch (error) {
    console.error('❌ Seeding failed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedEvents()
  .then(() => {
    console.log('\n✅ Event seeding completed successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Event seeding failed:', error);
    process.exit(1);
  });
