import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const events = [
  // Pre-Event Workshop
  {
    eventId: 'pre-udaan',
    title: 'Udaan - Roadmap to Entrepreneurship',
    description: 'Turn Ideas into Impact. A focused, hands-on workshop designed to help you transform your ideas into actionable business models. Learn practical startup frameworks, gain real-world insights, and take your first confident step into entrepreneurship.',
    category: 'workshops',
    date: new Date('2026-01-30'),
    startTime: new Date('2026-01-30T14:00:00'),
    endTime: new Date('2026-01-30T15:00:00'),
    venue: 'TBA',
    eligibility: 'Open to students, aspiring founders, and innovators',
    status: 'upcoming',
    speakerName: 'Prof. Chaitali & Dr. Pankaj Nandurkar',
  },
  // Day 1 Events - 16 total
  {
    eventId: 'd1-registration',
    title: 'Registration & Welcome',
    description: 'Check-in and receive your welcome kit',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T09:00:00'),
    endTime: new Date('2026-02-02T09:30:00'),
    venue: 'Main Entrance',
    status: 'upcoming',
  },
  {
    eventId: 'd1-inaugural',
    title: 'Inaugural Ceremony',
    description: 'Official opening of E-Summit 2026',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T09:30:00'),
    endTime: new Date('2026-02-02T10:30:00'),
    venue: 'Main Auditorium',
    status: 'upcoming',
    speakerName: 'Chief Guest',
  },
  {
    eventId: 'd1-ten-minute-million',
    title: 'The Ten Minute Deal: Pitch to Win',
    description: 'A high-energy pitching event where founders get just 10 minutes to present their startup to investors and industry leaders, aiming to secure funding, partnerships, and validation on the spot.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'SH-1',
    eligibility: 'TRL 4+ startups',
    prerequisites: 'Pitch deck required (PDF, max 15 slides)',
    status: 'upcoming',
    speakerName: '5 Venture Capitalists',
  },
  {
    eventId: 'd1-pitch-arena',
    title: 'Pitch Arena: Idea to Reality',
    description: 'Step into the arena! Founders pitch to top-tier mentors for real-time feedback and expert guidance to launch their ideas.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: '314, 315, 316',
    eligibility: 'Early stage startups, first-time founders welcome',
    status: 'upcoming',
    speakerName: '3 Industry Mentors',
  },
  {
    eventId: 'd1-incubator-summit',
    title: 'The Incubator Summit: Earn Your Launchpad',
    description: 'Where ideas earn their launchpad. Founders pitch to evaluators from five top incubation centers, competing for a spot and seed support to accelerate their venture.',
    category: 'pitching',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'SSC TIMSR',
    eligibility: 'Early stage startups',
    status: 'upcoming',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd1-ai-buildathon-start',
    title: 'AI Contest: The Innovation Challenge (Day 1)',
    description: 'Push the boundaries of AI. Tackle a real-world problem by designing and presenting an innovative, AI-driven solution. Showcase your technical skills and creativity to win the challenge.',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'SH 3',
    eligibility: 'All pass holders',
    prerequisites: 'Laptop with development environment',
    prizeAmount: 150000,
    status: 'upcoming',
    speakerName: 'Tech Mentors',
  },
  {
    eventId: 'd1-ipl-auction',
    title: 'IPL Auction: The Bid for Brilliance',
    description: 'Master the art of the deal. In this high-energy bidding game, build your dream team with a limited budget. Test your strategic thinking and financial savvy to outbid rivals and create a winning roster.',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: '601, TIMSR',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd1-biz-arena',
    title: 'Startup League Game: Build Your Empire',
    description: 'Step into the founder\'s seat. Run a virtual startup in this fast-paced simulation. Make critical decisions on product, marketing, and funding to outmaneuver competitors and dominate the market.',
    category: 'competitions',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T13:00:00'),
    venue: '301, TIMSR',
    eligibility: 'All pass holders',
    prizeAmount: 100000,
    status: 'upcoming',
    speakerName: 'Business Mentors',
  },
  {

    eventId: 'd1-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop',
    description: 'Unlock Your Creative Potential. Master the tools to solve complex problems and generate groundbreaking ideas. This hands-on workshop will equip you with a powerful framework for innovation.',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 522 & 523',
    eligibility: 'Silicon & Quantum Pass holders',
    prerequisites: 'Notepad recommended',
    status: 'upcoming',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd1-finance-marketing',
    title: 'Finance & Marketing for Startups Workshop',
    description: 'Build a Solid Foundation for Your Venture. Get essential, practical knowledge on managing your startup\'s finances and crafting marketing strategies that actually convert.',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 524 & 525',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd1-data-analytics',
    title: 'Data Analytics & Business Development Essentials Workshop',
    description: 'Make Smarter Decisions with Data. Learn to analyze market trends, track key metrics, and use data-driven insights to fuel your business growth and strategy.',
    category: 'workshops',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lab 526 & 527',
    eligibility: 'Silicon & Quantum Pass holders',
    prerequisites: 'Basic Excel knowledge',
    status: 'upcoming',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd1-startup-expo',
    title: 'The Startup Expo: Display Your First Prototype',
    description: 'Display Your First Prototype! Showcase your early-stage idea and prototype to the entire college community in our main lobby. A perfect chance to get your first users and feedback.',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T13:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Lobby Area',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-internship-fair',
    title: 'The Internship Fair: Build Your Founding Team (Day 1)',
    description: 'Build your founding team. Startups present their vision to recruit talented interns and full-time members, connecting ambitious talent with groundbreaking ideas.',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T10:00:00'),
    endTime: new Date('2026-02-02T17:00:00'),
    venue: 'Convocation Hall',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-networking-arena',
    title: 'Networking Arena (Lunch)',
    description: 'Open networking session during lunch - connect with entrepreneurs and investors',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T13:00:00'),
    endTime: new Date('2026-02-02T14:00:00'),
    venue: 'Multipurpose Hall 2nd Floor & Architecture Ground Floor',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd1-informals',
    title: 'Informals: Connect Beyond the Stage',
    description: 'Connect beyond the stage. An informal session for founders to mingle with judges, speakers, and mentors, turning conversations into valuable connections.',
    category: 'networking',
    date: new Date('2026-02-02'),
    startTime: new Date('2026-02-02T17:00:00'),
    endTime: new Date('2026-02-02T17:30:00'),
    venue: 'Multipurpose Hall 2nd Floor and TSAP ground floor',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  
  // Day 2 Events - 15 total
  {
    eventId: 'd2-registration',
    title: 'Day 2 Registration',
    description: 'Check-in for Day 2 events',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T09:00:00'),
    endTime: new Date('2026-02-03T09:30:00'),
    venue: 'Main Entrance',
    status: 'upcoming',
  },
  {
    eventId: 'd2-ten-minute-million',
    title: 'The Ten Minute Deal: Pitch to Win (Day 2)',
    description: 'A high-energy pitching event where founders get just 10 minutes to present their startup to investors and industry leaders, aiming to secure funding, partnerships, and validation on the spot.',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'SH-1',
    eligibility: 'TRL 4+ startups',
    prerequisites: 'Pitch deck required (PDF, max 15 slides)',
    status: 'upcoming',
    speakerName: '5 Venture Capitalists',
  },
  {
    eventId: 'd2-angel-roundtable',
    title: 'The Angel Investor\'s Roundtable: Capital Meets Innovation',
    description: 'An exclusive gathering where capital meets innovation. This roundtable brings together angel investors to vet and co-invest in the most promising early-stage companies, featuring founders selected from our Pitch Arena.',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T09:30:00'),
    endTime: new Date('2026-02-03T13:30:00'),
    venue: 'Seminar Hall',
    eligibility: 'Early stage startups with MVP',
    status: 'upcoming',
    speakerName: '5 Angel Investors',
  },
  {
    eventId: 'd2-incubator-summit',
    title: 'The Incubator Summit: Earn Your Launchpad (Day 2)',
    description: 'Where ideas earn their launchpad. Founders pitch to evaluators from five top incubation centers, competing for a spot and seed support to accelerate their venture.',
    category: 'pitching',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T13:00:00'),
    venue: 'SSC TIMSR',
    eligibility: 'Early stage startups',
    status: 'upcoming',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd2-ai-buildathon-final',
    title: 'AI Contest: The Innovation Challenge (Day 2 Finals)',
    description: 'Push the boundaries of AI. Tackle a real-world problem by designing and presenting an innovative, AI-driven solution. Showcase your technical skills and creativity to win the challenge.',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'SH 3',
    eligibility: 'All pass holders (participants only)',
    prizeAmount: 150000,
    status: 'upcoming',
    speakerName: 'Tech Judges',
  },
  {
    eventId: 'd2-ipl-auction',
    title: 'IPL Auction: The Bid for Brilliance (Day 2)',
    description: 'Master the art of the deal. In this high-energy bidding game, build your dream team with a limited budget. Test your strategic thinking and financial savvy to outbid rivals and create a winning roster.',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T09:30:00'),
    endTime: new Date('2026-02-03T13:30:00'),
    venue: '601, TIMSR',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd2-biz-arena',
    title: 'Startup League Game: Build Your Empire (Day 2)',
    description: 'Step into the founder\'s seat. Run a virtual startup in this fast-paced simulation. Make critical decisions on product, marketing, and funding to outmaneuver competitors and dominate the market.',
    category: 'competitions',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T13:00:00'),
    venue: '301, TIMSR',
    eligibility: 'All pass holders',
    prizeAmount: 100000,
    status: 'upcoming',
    speakerName: 'Business Mentors',
  },
  {
    eventId: 'd2-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop (Day 2)',
    description: 'Unlock Your Creative Potential. Master the tools to solve complex problems and generate groundbreaking ideas. This hands-on workshop will equip you with a powerful framework for innovation.',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 522 & 523',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd2-finance-marketing',
    title: 'Finance & Marketing for Startups Workshop (Day 2)',
    description: 'Build a Solid Foundation for Your Venture. Get essential, practical knowledge on managing your startup\'s finances and crafting marketing strategies that actually convert.',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 524 & 525',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd2-data-analytics',
    title: 'Data Analytics & Business Development Essentials Workshop (Day 2)',
    description: 'Make Smarter Decisions with Data. Learn to analyze market trends, track key metrics, and use data-driven insights to fuel your business growth and strategy.',
    category: 'workshops',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Lab 526 & 527',
    eligibility: 'Silicon & Quantum Pass holders',
    status: 'upcoming',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd2-internship-fair',
    title: 'The Internship Fair: Build Your Founding Team (Day 2)',
    description: 'Build your founding team. Startups present their vision to recruit talented interns and full-time members, connecting ambitious talent with groundbreaking ideas.',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T10:00:00'),
    endTime: new Date('2026-02-03T13:00:00'),
    venue: 'Convocation Hall',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd2-networking-arena',
    title: 'Networking Arena (Lunch)',
    description: 'Final networking opportunity during lunch with entrepreneurs and investors',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T13:00:00'),
    endTime: new Date('2026-02-03T14:00:00'),
    venue: 'Multipurpose Hall 2nd Floor & Architecture Ground Floor',
    eligibility: 'All pass holders',
    status: 'upcoming',
  },
  {
    eventId: 'd2-startup-youth-conclave',
    title: 'Startup Youth Conclave: Connect with Top E-Cells',
    description: 'Connect with Top E-Cells! Network with entrepreneurship cells from other colleges, share best practices, and build collaborations that go beyond your campus.',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T11:00:00'),
    endTime: new Date('2026-02-03T13:00:00'),
    venue: 'Seminar Hall 2nd floor TSAP',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'E-Cell Representatives',
  },
  {
    eventId: 'd2-panel-discussion',
    title: 'The Panel Discussion: Get the Final Insights',
    description: 'Get the Final Insights. Hear from our expert judges and speakers in a final panel discussion, followed by the closing ceremony to celebrate the day\'s winners and achievements.',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T14:00:00'),
    endTime: new Date('2026-02-03T17:00:00'),
    venue: 'Auditorium',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Industry Leaders',
  },
  {
    eventId: 'd2-closing',
    title: 'Closing Ceremony & Prize Distribution',
    description: 'Award ceremony, winner announcements, and closing remarks for E-Summit 2026',
    category: 'networking',
    date: new Date('2026-02-03'),
    startTime: new Date('2026-02-03T17:00:00'),
    endTime: new Date('2026-02-03T18:30:00'),
    venue: 'Auditorium',
    eligibility: 'All pass holders',
    status: 'upcoming',
    speakerName: 'Organizing Committee',
  },
];

async function seedEvents() {
  console.log('🌱 Starting event seeding...\n');

  try {
    // First, clear existing events
    console.log('🗑️  Clearing existing events...');
    await prisma.event.deleteMany({});
    console.log('✅ Existing events cleared\n');

    // Insert events
    console.log('📝 Creating events...\n');
    let successCount = 0;
    let errorCount = 0;

    for (const event of events) {
      try {
        await prisma.event.create({
          data: event,
        });
        console.log(`✅ Created: ${event.title} (${event.eventId})`);
        successCount++;
      } catch (error) {
        console.error(`❌ Failed to create ${event.eventId}:`, error);
        errorCount++;
      }
    }

    console.log('\n📊 Seeding Summary:');
    console.log(`✅ Successfully created: ${successCount} events`);
    console.log(`❌ Failed: ${errorCount} events`);
    console.log(`📈 Total: ${events.length} events`);

  } catch (error) {
    console.error('❌ Seeding failed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedEvents()
  .then(() => {
    console.log('\n✅ Event seeding completed successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Event seeding failed:', error);
    process.exit(1);
  });
