import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const events = [
  // Day 1 Events
  {
    eventId: 'd1-registration',
    title: 'Registration & Welcome',
    description: 'Check-in and receive your welcome kit',
    category: 'Networking',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T09:00:00Z'),
    endTime: new Date('2026-02-02T09:30:00Z'),
    venue: 'Main Entrance',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'None',
    prerequisites: 'Valid pass',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 1000,
    status: 'Active',
  },
  {
    eventId: 'd1-inaugural',
    title: 'Inaugural Ceremony',
    description: 'Official opening of E-Summit 2026',
    category: 'Ceremony',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T09:30:00Z'),
    endTime: new Date('2026-02-02T10:30:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'None',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 1000,
    status: 'Active',
    speakerName: 'Chief Guest',
  },
  {
    eventId: 'd1-ten-minute-million',
    title: 'Ten Minute Deal',
    description: 'Exclusive investor pitch session. Get 10 minutes to convince investors to fund your startup.',
    category: 'Investor Pitch',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Conference Hall A, TCET',
    prizeAmount: null,
    eligibility: 'Exclusive to Quantum Pass holders only',
    rules: 'Must have a registered startup. DPIIT certification preferred. 10-minute pitch with live feedback.',
    prerequisites: 'Registered startup, CIN number, Pitch deck, Financial projections',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 15,
    status: 'Active',
  },
  {
    eventId: 'd1-pitch-arena',
    title: 'Pitch Arena - Day 1',
    description: 'Showcase your startup idea and compete for prizes. Present your pitch to industry experts and investors.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: 50000,
    eligibility: 'Open to Pixel Pass, Silicon Pass, Quantum Pass holders and TCET Students',
    rules: 'Teams of 2-4 members. 5-minute pitch followed by 3-minute Q&A. Original ideas only.',
    prerequisites: 'Pitch deck (max 10 slides), Demo/prototype (optional)',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
  },
  {
    eventId: 'd1-incubator-summit',
    title: 'The Incubator Summit: Earn Your Launchpad',
    description: 'Where ideas earn their launchpad. Founders pitch to evaluators from five top incubation centers, competing for a spot and seed support to accelerate their venture.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'SSC TIMSR',
    prizeAmount: 100000,
    eligibility: 'Early stage startups',
    rules: 'Pitch to evaluators from top incubation centers',
    prerequisites: 'Early stage startup',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 30,
    status: 'Active',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd1-ai-buildathon-start',
    title: 'AI Contest: The Innovation Challenge (Day 1)',
    description: 'Push the boundaries of AI. Tackle a real-world problem by designing and presenting an innovative, AI-driven solution.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'SH 3',
    prizeAmount: 150000,
    eligibility: 'All pass holders',
    rules: 'Design and present AI-driven solution',
    prerequisites: 'Laptop with development environment',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 100,
    status: 'Active',
    speakerName: 'Tech Mentors',
  },
  {
    eventId: 'd1-ipl-auction',
    title: 'IPL Auction: The Bid for Brilliance',
    description: 'Master the art of the deal. In this high-energy bidding game, build your dream team with a limited budget.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: '601, TIMSR',
    prizeAmount: 50000,
    eligibility: 'All pass holders',
    rules: 'Bidding game with limited budget',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd1-biz-arena',
    title: 'Startup League Game: Build Your Empire',
    description: 'Step into the founder\'s seat. Run a virtual startup in this fast-paced simulation.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T13:00:00Z'),
    venue: '301, TIMSR',
    prizeAmount: 100000,
    eligibility: 'All pass holders',
    rules: 'Virtual startup simulation',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 40,
    status: 'Active',
    speakerName: 'Business Mentors',
  },
  {
    eventId: 'd1-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop',
    description: 'Unlock Your Creative Potential. Master the tools to solve complex problems and generate groundbreaking ideas.',
    category: 'Workshop',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Lab 522 & 523',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Hands-on workshop',
    prerequisites: 'Notepad recommended',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd1-finance-marketing',
    title: 'Finance & Marketing for Startups Workshop',
    description: 'Build a Solid Foundation for Your Venture. Get essential, practical knowledge on managing your startup\'s finances and crafting marketing strategies.',
    category: 'Workshop',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Lab 524 & 525',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Interactive workshop',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd1-data-analytics',
    title: 'Data Analytics & Business Development Essentials Workshop',
    description: 'Make Smarter Decisions with Data. Learn to analyze market trends, track key metrics, and use data-driven insights.',
    category: 'Workshop',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Lab 526 & 527',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Hands-on data analysis',
    prerequisites: 'Basic Excel knowledge',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd1-startup-expo',
    title: 'Startup Expo',
    description: 'Showcase your startup to attendees, investors, and media. Get a dedicated booth to display your products/services.',
    category: 'Exhibition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T09:00:00Z'),
    endTime: new Date('2026-02-02T18:00:00Z'),
    venue: 'Exhibition Area, TCET Campus',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'One booth per startup. Setup time: 8:00 AM - 9:00 AM.',
    prerequisites: 'Company profile, Marketing materials, Product/service demo',
    registrationDeadline: new Date('2026-02-04T23:59:00Z'),
    maxParticipants: 30,
    status: 'Active',
  },
  {
    eventId: 'd1-internship-fair',
    title: 'The Internship Fair: Build Your Founding Team (Day 1)',
    description: 'Build your founding team. Startups present their vision to recruit talented interns and full-time members.',
    category: 'Networking',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Convocation Hall',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'Startups recruit interns and team members',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 200,
    status: 'Active',
  },
  // Day 2 Events
  {
    eventId: 'd2-registration',
    title: 'Day 2 Registration',
    description: 'Check-in for Day 2 events',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T09:00:00Z'),
    endTime: new Date('2026-02-03T09:30:00Z'),
    venue: 'Main Entrance',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'None',
    prerequisites: 'Valid pass',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 1000,
    status: 'Active',
  },
  {
    eventId: 'd2-ten-minute-million',
    title: 'Ten Minute Deal (Day 2)',
    description: 'Second round of investor pitch sessions.',
    category: 'Investor Pitch',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Conference Hall A, TCET',
    prizeAmount: null,
    eligibility: 'Exclusive to Quantum Pass holders only',
    rules: 'Must have a registered startup. 10-minute pitch with live feedback.',
    prerequisites: 'Registered startup, CIN number, Pitch deck',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 15,
    status: 'Active',
  },
  {
    eventId: 'd2-angel-roundtable',
    title: 'Angel Investor Roundtable',
    description: 'Network with angel investors and get insights on fundraising, scaling, and building sustainable startups.',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T09:30:00Z'),
    endTime: new Date('2026-02-03T13:30:00Z'),
    venue: 'Conference Hall B, TCET',
    prizeAmount: null,
    eligibility: 'Exclusive to Quantum Pass holders only',
    rules: 'Interactive roundtable discussion. Come prepared with questions.',
    prerequisites: 'Basic understanding of startup funding',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 25,
    status: 'Active',
  },
  {
    eventId: 'd2-pitch-arena',
    title: 'Pitch Arena - Day 2',
    description: 'Second round of Pitch Arena. Present your refined pitch and compete for the grand prize.',
    category: 'Competition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: 100000,
    eligibility: 'Open to Pixel Pass, Silicon Pass, Quantum Pass holders and TCET Students',
    rules: 'Finalists from Day 1. 10-minute pitch followed by 5-minute Q&A.',
    prerequisites: 'Must have participated in Day 1 Pitch Arena',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 20,
    status: 'Active',
  },
  {
    eventId: 'd2-startup-expo',
    title: 'Startup Expo - Day 2',
    description: 'Continue showcasing your startup on Day 2. Connect with more attendees and potential investors.',
    category: 'Exhibition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T09:00:00Z'),
    endTime: new Date('2026-02-03T18:00:00Z'),
    venue: 'Exhibition Area, TCET Campus',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'Continuation of Day 1 expo. Same booth assignments.',
    prerequisites: 'Must have registered for Day 1 Startup Expo',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 30,
    status: 'Active',
  },
  {
    eventId: 'd2-keynote-session',
    title: 'Keynote Session - Future of Tech',
    description: 'Explore emerging technologies and their impact on startups. Featuring AI, Web3, and sustainability experts.',
    category: 'Talk',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T11:00:00Z'),
    endTime: new Date('2026-02-03T12:30:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'First come, first served seating. Panel discussion format.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 500,
    status: 'Active',
    speakerName: 'Panel of tech industry leaders',
  },
  {
    eventId: 'd2-networking-lunch',
    title: 'Networking Lunch - Day 2',
    description: 'Continue building connections over lunch on Day 2.',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T13:00:00Z'),
    endTime: new Date('2026-02-03T14:00:00Z'),
    venue: 'Cafeteria, TCET',
    prizeAmount: null,
    eligibility: 'Open to Silicon Pass and Quantum Pass holders',
    rules: 'Lunch provided. Structured networking activities.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 150,
    status: 'Active',
  },
  {
    eventId: 'd2-workshop-fundraising',
    title: 'Workshop: Fundraising Essentials',
    description: 'Learn the art of fundraising from VCs and angel investors. Pitch practice included.',
    category: 'Workshop',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T15:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Conference Hall C, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'Interactive workshop. Prepare questions.',
    prerequisites: 'Basic understanding of startup financing',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
  },
  {
    eventId: 'd1-panel-discussion',
    title: 'Panel Discussion: Scaling Startups in India',
    description: 'Panel of successful founders discussing challenges and strategies for scaling startups in the Indian market.',
    category: 'Talk',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T14:30:00Z'),
    endTime: new Date('2026-02-02T16:00:00Z'),
    venue: 'Seminar Hall 1, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'Open Q&A session at the end.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 200,
    status: 'Active',
  },
  {
    eventId: 'd2-panel-discussion',
    title: 'Panel Discussion: Women in Entrepreneurship',
    description: 'Inspiring panel featuring successful women entrepreneurs sharing their journey and insights.',
    category: 'Talk',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T14:00:00Z'),
    endTime: new Date('2026-02-03T15:30:00Z'),
    venue: 'Seminar Hall 1, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'Open to all genders. Interactive discussion format.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 200,
    status: 'Active',
  },
  {
    eventId: 'd1-hackathon',
    title: '24-Hour Startup Hackathon',
    description: 'Build a working prototype or business solution in 24 hours. Judged on innovation, feasibility, and presentation.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T18:00:00Z'),
    endTime: new Date('2026-02-03T18:00:00Z'),
    venue: 'Computer Lab, TCET',
    prizeAmount: 75000,
    eligibility: 'Open to all pass holders',
    rules: 'Teams of 2-5 members. Must stay for full 24 hours. All code/work done on-site.',
    prerequisites: 'Laptop, charger, programming skills',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 100,
    status: 'Active',
  },
  {
    eventId: 'd1-case-competition',
    title: 'Business Case Competition',
    description: 'Solve real-world business challenges. Analyze case studies and present strategic solutions.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T10:00:00Z'),
    endTime: new Date('2026-02-02T16:00:00Z'),
    venue: 'Classroom Block A, TCET',
    prizeAmount: 40000,
    eligibility: 'Open to Pixel Pass, Silicon Pass, and Quantum Pass holders',
    rules: 'Teams of 3-4 members. Case study released on spot. 4 hours preparation + 15 min presentation.',
    prerequisites: 'Business acumen, analytical skills',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 60,
    status: 'Active',
  },
  {
    eventId: 'd1-masterclass-marketing',
    title: 'Masterclass: Growth Marketing for Startups',
    description: 'Learn growth hacking techniques and marketing strategies from industry experts.',
    category: 'Workshop',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T11:00:00Z'),
    endTime: new Date('2026-02-02T13:00:00Z'),
    venue: 'Lab 302, TCET',
    prizeAmount: null,
    eligibility: 'Open to Silicon Pass and Quantum Pass holders',
    rules: 'Bring laptop for hands-on exercises.',
    prerequisites: 'Basic marketing knowledge',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
  },
  {
    eventId: 'd2-masterclass-product',
    title: 'Masterclass: Product Management',
    description: 'Deep dive into product development, user research, and product-market fit strategies.',
    category: 'Workshop',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T12:00:00Z'),
    venue: 'Lab 303, TCET',
    prizeAmount: null,
    eligibility: 'Open to Silicon Pass and Quantum Pass holders',
    rules: 'Interactive session with case studies.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
  },
  {
    eventId: 'd1-mentor-connect',
    title: 'One-on-One Mentor Connect',
    description: 'Get personalized mentorship from industry leaders. 30-minute private sessions.',
    category: 'Networking',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T15:00:00Z'),
    endTime: new Date('2026-02-02T18:00:00Z'),
    venue: 'Meeting Rooms, TCET',
    prizeAmount: null,
    eligibility: 'Exclusive to Quantum Pass holders',
    rules: 'Pre-book your slot. Come prepared with specific questions.',
    prerequisites: 'Brief about your startup/idea',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 20,
    status: 'Active',
  },
  {
    eventId: 'd2-investor-meet',
    title: 'Speed Dating with Investors',
    description: 'Quick 10-minute sessions with multiple investors. Make your pitch count!',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T16:00:00Z'),
    endTime: new Date('2026-02-03T18:00:00Z'),
    venue: 'Conference Hall A, TCET',
    prizeAmount: null,
    eligibility: 'Exclusive to Quantum Pass holders',
    rules: 'Each startup gets 5 rounds of 10 min each with different investors.',
    prerequisites: 'Elevator pitch, one-pager, business plan',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 25,
    status: 'Active',
  },
  {
    eventId: 'd1-innovation-challenge',
    title: 'Social Innovation Challenge',
    description: 'Develop innovative solutions to social problems. Focus on impact and sustainability.',
    category: 'Competition',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T09:00:00Z'),
    endTime: new Date('2026-02-02T15:00:00Z'),
    venue: 'Seminar Hall 2, TCET',
    prizeAmount: 30000,
    eligibility: 'Open to all pass holders',
    rules: 'Teams of 2-5. Focus on social impact, feasibility, and scalability.',
    prerequisites: 'Passion for social change',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 40,
    status: 'Active',
  },
  {
    eventId: 'd2-closing-ceremony',
    title: 'Closing Ceremony & Prize Distribution',
    description: 'Celebrate E-Summit 2026 with prize distribution, performances, and closing keynote.',
    category: 'Ceremony',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T18:30:00Z'),
    endTime: new Date('2026-02-03T20:30:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'Mandatory attendance for competition winners.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-03T18:00:00Z'),
    maxParticipants: 1000,
    status: 'Active',
  },
  {
    eventId: 'd1-startup-clinic',
    title: 'Startup Health Check Clinic',
    description: 'Get your startup evaluated by experts. Receive feedback on business model, product, and strategy.',
    category: 'Networking',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T12:00:00Z'),
    endTime: new Date('2026-02-02T17:00:00Z'),
    venue: 'Meeting Rooms 1-5, TCET',
    prizeAmount: null,
    eligibility: 'Open to Silicon Pass and Quantum Pass holders',
    rules: 'Book 45-min slots. Bring business plan and pitch deck.',
    prerequisites: 'Working startup or detailed business plan',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 30,
    status: 'Active',
  },
  {
    eventId: 'd1-keynote-session',
    title: 'Keynote Session - Building Unicorns',
    description: 'Learn from successful entrepreneurs who built unicorn startups. Interactive Q&A session included.',
    category: 'Talk',
    date: new Date('2026-02-02T00:00:00Z'),
    startTime: new Date('2026-02-02T11:00:00Z'),
    endTime: new Date('2026-02-02T12:30:00Z'),
    venue: 'Main Auditorium, TCET',
    prizeAmount: null,
    eligibility: 'Open to all pass holders',
    rules: 'First come, first served seating. Q&A session at the end.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-01T23:59:00Z'),
    maxParticipants: 500,
    status: 'Active',
    speakerName: 'TBA',
    speakerBio: 'Renowned entrepreneur and investor',
  },
  {
    eventId: 'd2-incubator-summit',
    title: 'The Incubator Summit: Earn Your Launchpad (Day 2)',
    description: 'Where ideas earn their launchpad. Founders pitch to evaluators from five top incubation centers, competing for a spot and seed support to accelerate their venture.',
    category: 'Competition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T13:00:00Z'),
    venue: 'SSC TIMSR',
    prizeAmount: null,
    eligibility: 'Early stage startups',
    rules: 'Pitch to evaluators from top incubation centers',
    prerequisites: 'Early stage startup',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 30,
    status: 'Active',
    speakerName: '5 Incubation Centre Evaluators',
  },
  {
    eventId: 'd2-ai-buildathon-final',
    title: 'AI Contest: The Innovation Challenge (Day 2 Finals)',
    description: 'Push the boundaries of AI. Tackle a real-world problem by designing and presenting an innovative, AI-driven solution. Showcase your technical skills and creativity to win the challenge.',
    category: 'Competition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'SH 3',
    prizeAmount: 150000,
    eligibility: 'All pass holders (participants only)',
    rules: 'Design and present AI-driven solution',
    prerequisites: 'Laptop with development environment',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 100,
    status: 'Active',
    speakerName: 'Tech Judges',
  },
  {
    eventId: 'd2-ipl-auction',
    title: 'IPL Auction: The Bid for Brilliance (Day 2)',
    description: 'Master the art of the deal. In this high-energy bidding game, build your dream team with a limited budget. Test your strategic thinking and financial savvy to outbid rivals and create a winning roster.',
    category: 'Competition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T09:30:00Z'),
    endTime: new Date('2026-02-03T13:30:00Z'),
    venue: '601, TIMSR',
    prizeAmount: 50000,
    eligibility: 'All pass holders',
    rules: 'Bidding game with limited budget',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Business Strategy Mentors',
  },
  {
    eventId: 'd2-biz-arena',
    title: 'Startup League Game: Build Your Empire (Day 2)',
    description: 'Step into the founder\'s seat. Run a virtual startup in this fast-paced simulation. Make critical decisions on product, marketing, and funding to outmaneuver competitors and dominate the market.',
    category: 'Competition',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T13:00:00Z'),
    venue: '301, TIMSR',
    prizeAmount: 100000,
    eligibility: 'All pass holders',
    rules: 'Virtual startup simulation',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 40,
    status: 'Active',
    speakerName: 'Business Mentors',
  },
  {
    eventId: 'd2-design-thinking',
    title: 'Design Thinking & Innovation Strategy Workshop (Day 2)',
    description: 'Unlock Your Creative Potential. Master the tools to solve complex problems and generate groundbreaking ideas. This hands-on workshop will equip you with a powerful framework for innovation.',
    category: 'Workshop',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Lab 522 & 523',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Hands-on workshop',
    prerequisites: 'Notepad recommended',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Design Expert',
  },
  {
    eventId: 'd2-finance-marketing',
    title: 'Finance & Marketing for Startups Workshop (Day 2)',
    description: 'Build a Solid Foundation for Your Venture. Get essential, practical knowledge on managing your startup\'s finances and crafting marketing strategies that actually convert.',
    category: 'Workshop',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Lab 524 & 525',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Interactive workshop',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Industry Expert',
  },
  {
    eventId: 'd2-data-analytics',
    title: 'Data Analytics & Business Development Essentials Workshop (Day 2)',
    description: 'Make Smarter Decisions with Data. Learn to analyze market trends, track key metrics, and use data-driven insights to fuel your business growth and strategy.',
    category: 'Workshop',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T17:00:00Z'),
    venue: 'Lab 526 & 527',
    prizeAmount: null,
    eligibility: 'Silicon & Quantum Pass holders',
    rules: 'Hands-on data analysis',
    prerequisites: 'Basic Excel knowledge',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 50,
    status: 'Active',
    speakerName: 'Data Scientist',
  },
  {
    eventId: 'd2-internship-fair',
    title: 'The Internship Fair: Build Your Founding Team (Day 2)',
    description: 'Build your founding team. Startups present their vision to recruit talented interns and full-time members, connecting ambitious talent with groundbreaking ideas.',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T10:00:00Z'),
    endTime: new Date('2026-02-03T13:00:00Z'),
    venue: 'Convocation Hall',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'Startups recruit interns and team members',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 200,
    status: 'Active',
  },
  {
    eventId: 'd2-startup-youth-conclave',
    title: 'Startup Youth Conclave: Connect with Top E-Cells',
    description: 'Connect with Top E-Cells! Network with entrepreneurship cells from other colleges, share best practices, and build collaborations that go beyond your campus.',
    category: 'Networking',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T11:00:00Z'),
    endTime: new Date('2026-02-03T13:00:00Z'),
    venue: 'Seminar Hall 2nd floor TSAP',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'Informal networking session',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-02T23:59:00Z'),
    maxParticipants: 100,
    status: 'Active',
    speakerName: 'E-Cell Representatives',
  },
  {
    eventId: 'd2-closing',
    title: 'Closing Ceremony & Prize Distribution',
    description: 'Award ceremony, winner announcements, and closing remarks for E-Summit 2026',
    category: 'Ceremony',
    date: new Date('2026-02-03T00:00:00Z'),
    startTime: new Date('2026-02-03T17:00:00Z'),
    endTime: new Date('2026-02-03T18:30:00Z'),
    venue: 'Auditorium',
    prizeAmount: null,
    eligibility: 'All pass holders',
    rules: 'Mandatory attendance for competition winners.',
    prerequisites: 'None',
    registrationDeadline: new Date('2026-02-03T18:00:00Z'),
    maxParticipants: 1000,
    status: 'Active',
    speakerName: 'Organizing Committee',
  },
];

async function seedEvents() {
  console.log('🌱 Seeding events...');

  try {
    // Clear existing events
    console.log('🗑️  Clearing existing events...');
    await prisma.event.deleteMany({});

    // Create events
    console.log('📅 Creating events...');
    for (const event of events) {
      const created = await prisma.event.create({
        data: event,
      });
      console.log(`✅ Created: ${created.eventId} - ${created.title}`);
    }

    console.log(`\n✨ Successfully seeded ${events.length} events!`);
    
    // Display summary
    console.log('\n📊 Event Summary:');
    console.log('─'.repeat(80));
    
    const categories = await prisma.event.groupBy({
      by: ['category'],
      _count: true,
    });
    
    categories.forEach((cat) => {
      console.log(`${cat.category}: ${cat._count} events`);
    });
    
    console.log('─'.repeat(80));
    console.log(`\nTotal Events: ${events.length}`);
    
  } catch (error) {
    console.error('❌ Error seeding events:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedEvents()
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
